### DISCUSSION TITLE
How to make navbar-bg-color and sidebar-bg-color change with the light/dark theme?

### DISCUSSION THREAD

**Discussion by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2313] [Q&A] [answered]
I want to customize a new background color and have set `$bg-color` in palette.scss, but  it does not contain navbar or sidebar.Then I set remaining colors on index.scss. Those colors are constant. 
Which file or method makes `--navbar-bg-color` and `--sidebar-bg-color` change with the light/dark theme?

```scss
/* palette.scss */
$bg-color: (
  light: #fefefe,
  dark: #252232,
);

/* index.scss */
.navbar {
  background: #252232;
}
.sidebar {
  background: #252232;
}
```
