### DISCUSSION TITLE
How to customize text size?

### DISCUSSION THREAD

**Discussion by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2931] [Q&A] [answered]
Updated the latest version today and found that the font of the article has become larger.

I looked at the styles config in the documentation and found that there are only `font-family` options in palette.scss.

Is it possible to set `font-size` options directly in index.scss? Or is there a better option?

**Comment by Mister-Hope** [comment, marked as answer]
~~What do you mean with "the font of the article has become larger"~~

Oh I got you, font size you mean.

The font-size on pc layout is increased to 18px, and you can revert the previous outlook by adding:

```scss
// .vuepress/styles/index.scss
@media (min-width: 1440px) {
  body {
    font-size: 16px;
  }
}
```
