### DISCUSSION TITLE
github action 发布时报错

### DISCUSSION THREAD

**Discussion by zuihou** [vuepress-theme-hope/vuepress-theme-hope#3131] [Q&A]
```
name: deploy

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      - name: rm yml
        run: |
          rm -rf pnpm-lock.yaml
          rm -rf docs/.vuepress/.cache/ 
          rm -rf docs/.vuepress/.temp/  
          rm -rf docs/.vuepress/dist/  

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: | 
          pnpm run build

      - name: deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: docs/.vuepress/dist/
          remote_path: /data_prod/webapp/lamp-doc/dist/
          remote_host: ${{ secrets.MY_CENTOS_HOST }}
          remote_port: ${{ secrets.MY_CENTOS_PORT }}
          remote_user: ${{ secrets.MY_CENTOS_USERNAME }}
          remote_key: ${{ secrets.MY_CENTOS_RSA_PRIVATE_KEY }}
```

使用github action发布，执行Docs build步骤时，报错如下：

<img width="1832" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/8500410/94a35ed7-a0f6-41a6-91e3-6e8b66373cc8">

请问是什么原因呢？该如何排查呢
