### DISCUSSION TITLE
升级版本后 index.scss 中自定义样式失效

### DISCUSSION THREAD

**Discussion by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#3392] [Q&A] [answered]
当前旧版的页面： https://hut.ao
带有预览的 PR：https://github.com/DGP-Studio/Snap.Hutao.Docs/pull/46
相关文件：https://github.com/DGP-Studio/Snap.Hutao.Docs/blob/f5e11cf577b15c1ab07808c5f0f24b51e161f446/docs/.vuepress/styles/index.scss

想模仿主题官网将 heroTitle 部分的高度提高，于是将官方库里的这一段代码复制进了我自己的 `index.scss`
```scss
.home {
  .vp-hero-info-wrapper {
    min-height: 600px;
  }
}
```
然而测试后发现并没有生效，而且我之前添加的用于去除导航栏外链图标的样式也失效了。想问下该如何解决。

**Comment by Mister-Hope** [comment, marked as answer]
We changed className like `home` to `vp-home` to ensure they don't affect users' styles.

**Reply by Masterain98** [reply]
~~I tried to switch to it, but it's still not working. Also, I found the class name in scss that I used to remove the external link icon was not changed, but its change is not applied as well. ~~
```scss
.vp-hero-info-wrapper {
  min-height: 600px;
}

header.vp-navbar {
  svg.external-link-icon {
    position: relative;
    display: none;
    color: var(--external-link-icon-color);
    vertical-align: middle;
    top: -1px;
  }
}
```
This one is working now.
