### ISSUE TITLE
[Feature Request] icon attribute should support image

### ISSUE THREAD

**Issue by trydofor** [vuepress-theme-hope/vuepress-theme-hope#2012]
### Describe the feature

in frontmatter of home.md, the `icon` attr reder different

```yml
home: true
icon: /my-icon.png # ①
features:
  - icon: /my-icon.png  # ②
```

① `<span class="icon iconfont icon-/my-icon.png"></span>`
② `<img class="icon" src="/my-icon.png">`

they should works as same as ② (both support css and img)

* config in `ts` - `{ text: '', icon: '/my-icon.png', link: '' }`
* frontmatter in `md`
* navbar.icon
