### ISSUE TITLE
backToTop是否支持更换图标

### ISSUE THREAD

**Issue by kk305cs** [vuepress-theme-hope/vuepress-theme-hope#2237]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

backToTop是否支持更换图标？如何更换？

**Comment by Mister-Hope** [comment]
我觉得你不启用主题的，然后自己写一个就行了

**Comment by Mister-Hope** [comment]
不过的确可以提供自定义图标的能力

**Comment by kk305cs** [comment]
小小建议，可以提供一个~

**Comment by Mister-Hope** [comment]
If anyone need this:

```css
.back-to-top {
  background-image: url(YOUR_IMAGE)
}

.back-to-top svg {
   display: none !important;
}
```

Or, anyone can feel free to copy and modify https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/components/src/client/components/BackToTop.ts
