### ISSUE TITLE
[Feature Request] Improvements to TOC style

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2311]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I recently saw a beautiful blog page, with the toc being pinned to the center of the right side of the page.

sample page：https://moonvy.com/blog/post/2022/diffusion-accelerates-diffusion/#%E7%BB%98%E7%94%BB%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7
![image](https://user-images.githubusercontent.com/28252913/196731097-4ab88708-efc8-4c83-8531-4fb6f591f6e8.png)

**Comment by Mister-Hope** [comment]
You are free to customize to styles.

**Comment by rockbenben** [comment]
I have set `$bg-color` in palette.scss, but  it does not contain navbar or sidebar.Then I set remaining colors on index.scss. Those colors are constant. 
Which file or method makes `--navbar-bg-color` and `--sidebar-bg-color` change with the light/dark theme?

```scss
/* palette.scss */
$bg-color: (
  light: #fefefe,
  dark: #252232,
);

/* index.scss */
.navbar {
  background: #252232;
}
.sidebar {
  background: #252232;
}
```
