### ISSUE TITLE
[Feature Request] enable scroll on category and tag list on article page

### ISSUE THREAD

**Issue by JeremieLitzler** [vuepress-theme-hope/vuepress-theme-hope#2771]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

It is simple: when you star to have quite a few categories or tags, the `category-wrapper` and / or `tag-wrapper` don't provide a very nice UX for the visitor.

Indeed he has to scroll all the way down the article page to see and select the last categories or tags.

Using a small CSS fix, we can solve that:

```css
.blog-info-list .category-wrapper .category-list-wrapper,
.blog-info-list .tag-wrapper .tag-list-wrapper {
    max-height: 30em;
    overflow-y: scroll;
}

```

Before you would get this:

![image](https://user-images.githubusercontent.com/2410556/218278044-c66f9177-0b62-4f41-b848-1ec0df7fba73.png)

After, you have that:

![image](https://user-images.githubusercontent.com/2410556/218278004-249e8257-eb5d-4e09-8999-a9b220524231.png)

Plus, it is done already on the timeline, so it makes sense to have it here as well.

What do you think?
