### ISSUE TITLE
[Feature Request] code 标签样式优化

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#3224]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

原始的 code 标签在正文中显示效果居下，看着很别扭，如下图：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41162158/21daabc0-a110-4146-9152-dcc8408b0d41)

经过调整后的效果如下：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41162158/4a2e6213-c23f-444e-a8a9-286199470ba5)

需要加入以下代码：

```scss
p > code,
ul > li > code,
ol > li > code {
  vertical-align: text-top;
}
```
