### ISSUE TITLE
[Feature Request] 关于一些基础样式污染的一些想法

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#3305]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我在使用过程中，想要演示自己做的组件功能，最简单的办法就是直接在 md 中使用组件，这样复杂一些的框架也能直接使用，因为我会将需要的依赖同时集成到文档中。

但是使用过程中发现一些基础样式会被污染（如：table、p、h等基础标签），如果使用隔离，那么组件演示将非常的麻烦，基本上就是要虚拟出一套我的开发环境。

我就想文档框架是否能做到以下功能从而减少对组件演示的污染问题
1. 在解析 md 成 html 时，将基础的标签都加上 class。如：`<table class="vp-table">`
2. 覆盖样式时直接使用 `table.vp-table`，我想这样应该能规避七成的样式污染问题

**Comment by Mister-Hope** [comment]
It's very usual for a working env to have its own "normalize stylesheet".

Your component may need to have its own "style guard".

I refused to call this a "style pollution".

If you are working a full set of component library, where every users must not add A SINGLE LINE style to ANY tags, extend this theme and remove the normalize part.

**Comment by WangJincheng4869** [comment]
> It's very usual for a working env to have its own "normalize stylesheet".
> 
> Your component may need to have its own "style guard".
> 
> I refused to call this a "style pollution".
> 
> If you are working a full set of component library, where every users must not add A SINGLE LINE style to ANY tags, and should only use and customize things you provide, extend this theme and remove the normalize part.
> 
> Other users should not suffer for the extra size and rendering burden.

你说的很对啊，所有的 css 样式我们都加了 class，但由于 vp 直接给标签附加了样式出现了以下情况，我拿3 Table 举例：

假如：
1.  vp 对 table 的样式设置为 `border: 1px solid #000` ，而其他地方用到表格没对 `border` 进行设置，那么就会出现所有的地方都有边框，因为 `table` 元素默认是没有边框的。
2.  vp 将 table 的 `display` 设置为 `block`，其他地方没有设置 `display` ，其用到的表格也会变成 `block`。

这就很尴尬.....


所以我在我的项目中的 vp `index.scss` 中是这样处理的：
```scss
table {
  display: table;
  margin: initial;
  overflow-x: initial;
  border-collapse: separate;

  tr:nth-child(2n) {
    background: initial;
  }

  th,
  td {
    padding: initial;
    border: initial;
  }
}

table:not([class]) {
  display: block;
  overflow-x: auto;
  margin: 1rem 0;
  border-collapse: collapse;

  tr:nth-child(2n) {
    background: var(--bg-color-secondary);
  }

  th,
  td {
    padding: 0.6em 1em;
    border: 1px solid var(--border-color-dark);
  }
}
```
