### ISSUE TITLE
[Bug] pnpm 默认生成配置无法构建 

### ISSUE THREAD

**Issue by lxl66566** [vuepress-theme-hope/vuepress-theme-hope#3332]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

使用 pnpm 指令 `pnpm create vuepress-theme-hope my-docs` 创建 blog 模版项目后，生成的 *deploy-docs.yml* 并不能成功构建，报错：
> Error: Error: No pnpm version is specified.

需要指定：
```yml {5}
- name: 安装 pnpm
  uses: pnpm/action-setup@v2
  with:
    run_install: true
    version: 8 # add
```

### Additional context

```
pnpm create vuepress-theme-hope my-docs
cd my-docs
git add .
git commit -m 'test'
git push ... main
```
and you can see it
