### ISSUE TITLE
[Bug] navbar can't scroll if window is narrow

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#3801]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Example:

<img width="766" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/a1ad8ca0-5033-4e43-aef5-b2c7f49d456e">

I've tried this css:

```css

#navbar {
  overflow-x: auto;
}

#navbar::-webkit-scrollbar {
  display: none;
}

#navbar {
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* Internet Explorer 10+ */
}
```

It makes the navbar scrollable, but the dropdown title disappears.

My suggestion is:

1. Make the navbar scroll horizontally.
2. Pin the logo to the leftmost.
3. Scale down the size of the search box when the window is narrow.

Thanks for your excellent theme!
