### ISSUE TITLE
[Bug] I am not use if it is a bug or not? I can not deploy it in vercel

### ISSUE THREAD

**Issue by bbruceyuan** [vuepress-theme-hope/vuepress-theme-hope#4167]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

> repo: https://github.com/bbruceyuan/bbruceyuan.github.io
> you can find my config there. 

pageckage list:
```json
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.9",
    "@vuepress/helper": "2.0.0-rc.28",
    "@vuepress/plugin-feed": "^2.0.0-rc.30",
    "@vuepress/plugin-google-analytics": "^2.0.0-rc.30",
    "@vuepress/plugin-redirect": "^2.0.0-rc.30",
    "@vuepress/plugin-sitemap": "^2.0.0-rc.30",
    "@vuepress/plugin-umami-analytics": "^2.0.0-rc.30",
    "mathjax-full": "3.2.2",
    "vue": "^3.4.27",
    "vuepress": "2.0.0-rc.9",
    "vuepress-plugin-search-pro": "2.0.0-rc.43",
    "vuepress-theme-hope": "v2.0.0-rc.43"
  }
```

1. on mac, it works well
step1: npm i --force.  (I have to add --force. Or I faied to install the proper package. but i dont know why?
step: npm run docs:dev

2. on github action. if I add npm i --force, it works well too
config: 
```yaml
name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: '20'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install --force
          npm run docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.VUEPRESS_TOKEN }}
```

3. BUT in vecel. Even if I add `npm i --force`, it failed.
case1: if i didnot add `--force`, it failed while install package. 
case2: if I did add `--force`, it can finish all process but not render well. 
config: 
<img width="835" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/16234167/9d78e8f7-4bde-4ab2-8961-6e80a18aa16f">

situation: You can find how it works now: https://bbruceyuan-github-io-bbruceyuans-projects.vercel.app/ 
The error in installation process: 
```error
Error: useClientData() is called without provider.
    at useClientData (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:705:11)
    at useRouteLocale (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:713:28)
    at useLocaleConfig (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:897:23)
    at useCopyCode (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:1644:18)
    at Object.setup (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:1710:5)
    at setup (file:///vercel/path0/docs/.vuepress/.temp/.server/app.D3Eby4au.mjs:3517:59)
    at callWithErrorHandling (/vercel/path0/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (/vercel/path0/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6048:25)
    at setupComponent (/vercel/path0/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6035:36)
    at renderComponentVNode (/vercel/path0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:358:15)
```
<img width="1420" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/16234167/bed94efd-d4f9-40cf-8550-e2a82b685e49">

4. it is just a question but it doesn't count. 
why should i have to add `--force` if I upgrade my project from v2.0.0-rc.2 to v2.0.0-rc.43?
