### ISSUE TITLE
[Bug] 侧边栏折叠要点两次了

### ISSUE THREAD

**Issue by bihell** [vuepress-theme-hope/vuepress-theme-hope#4190]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

新功能设置默认侧边栏是否折叠，设置之后我发现要点两次了

代码：
```
---
title: 详细测评
icon: fluent-mdl2:preview-link
index: false
dir:
#  collapsible: false
  expanded: true
  order: 5
article: false
---

<Catalog />
```

直接访问我站点查看 ：
https://bigdata.icu/vps/guide.html
