### ISSUE TITLE
[Suggestion] Remove the solid perfix of hint container

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4477]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I upgraded to the latest version and it looks very beautiful! And I notice that the note hint container is a little different than others, because the prefix is a lighter color, others are not.

<img width="1469" alt="image" src="https://github.com/user-attachments/assets/063a9272-a5e1-4ba6-a462-961ed66fb954">

I think the note container looks more natural than the others. Because other components like tabs, details, demo don't have deeper solid perfix like hit containers.

So I suggest removing the solid perfix of all the hint containers, which can give the theme a flat and uniform style. How do you think?

```css
.hint-container.important, .hint-container.info, .hint-container.note, .hint-container.tip, .hint-container.warning, .hint-container.caution {
  border-inline-start-width: unset;
  border-inline-start-style: unset;
}
```

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/989f5df7-f90f-41f2-91cf-4e0719a08a40">
