### ISSUE TITLE
[Feature Request]永久链接能否支持？

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#4534]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

类似 hexo 永久链接支持，会不错：

```yml
## abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32 进制
  rep: hex        #support dec(default) and hex  算法
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  ## Generate categories from directory-tree
  ## depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(default)
     depth:        #3(default)
     over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.
```

link: [https://bornforthis.cn/blog/hexo/01-hexo-link-setting.html](https://bornforthis.cn/blog/hexo/01-hexo-link-setting.html)
