### ISSUE TITLE
[Bug] macOS 下 Chromium 中文字体问题

### ISSUE THREAD

**Issue by xrgzs** [vuepress-theme-hope/vuepress-theme-hope#4890]
### Checklist

- [x] I am using **LTS** version of Node.js.
- [x] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [x] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [x] I followed the docs and I double checked my configuration.
- [x] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

macOS 下的 Chromium 系浏览器中文字体有问题，错误回落到了华文黑体（`STHeiti`），风格与英文字体差异太大，导致观感不统一。需要替换 `STHeiti` 为 `Pingfang SC`，或者最好不定义 CJK 字体。

```css
:root {
    --vp-font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", STHeiti, "Microsoft YaHei", SimSun, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    --vp-font-heading: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", STHeiti, "Microsoft YaHei", SimSun, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```

### Additional context

Google Chrome 136.0.7103.93:

![](https://github.com/user-attachments/assets/6a47ee70-4313-4d32-bb1e-656c28aa06de)

默认字体设置：

![](https://github.com/user-attachments/assets/3caa447f-92e7-4c86-b952-16dd123f1333)

Safari 18.4 (20621.1.15.11.10)正常:

![](https://github.com/user-attachments/assets/9e237de6-776b-4421-8c25-e7dc216a639d)

参考文章：

- https://sspai.com/post/87960
- https://lrd.im/blog/2022-01-17

可以参考 VitePress 的处理方式：

https://github.com/vuejs/vitepress/blob/827259b0d5e4032ec6e7a696969ecc2ed77c6bc2/src/client/theme-default/styles/vars.css#L259-L277

其对中文标点符号还进行了特殊处理（可选）：

https://github.com/vuejs/vitepress/blob/827259b0d5e4032ec6e7a696969ecc2ed77c6bc2/src/client/theme-default/styles/fonts.css#L151-L193
