### ISSUE TITLE
[Bug] .vuepress/styles/index.styl不能覆盖主题样式

### ISSUE THREAD

**Issue by yzhang921** [vuepress-theme-hope/vuepress-theme-hope#706]
## Screenshots

docs/.vuepress/styles/index.styl

增加样式

```css
.navbar {
  box-shadow: 0 2px 3px var(--card-shadow-color);
}
```

![image](https://user-images.githubusercontent.com/6037522/124059246-581c5e80-da5d-11eb-8aeb-a372e7b6c86e.png)

![image](https://user-images.githubusercontent.com/6037522/124059175-36bb7280-da5d-11eb-9ec9-fc663e919edf.png)
